### ISSUE TITLE
声音不好听，求炮弹声

### ISSUE THREAD

**Issue by binbin-smile** [poboke/ActivatePowerMode#10]
如题

**Comment by poboke** [comment]
目前是可以修改音效的，你可以把自定义的音效文件存储为`~/.powermode.aiff`，插件会优先使用这个路径的音效。

**Comment by poboke** [comment]
下载代码，打开工程，按`command + b`编译，然后完全退出Xcode(在任务栏用右键退出)再重新打开Xcode，会出现一个加载插件的提示框，加载后就能看到效果了。
我只在Xcode7.0以上测试过，6.x听说用不了，有空我下载个旧版本看看。

**Comment by poboke** [comment]
应用程序里的Xcode没有改名吧，如果编译有错误的话，可以把错误信息贴出来

**Comment by manfar** [comment]
附件将于 2016年1月16日过期

> 在 2015年12月17日，下午4:07，poboke <notifications@github.com <mailto:notifications@github.com>> 写道：
> 
> 应用程序里的Xcode没有改名吧，如果编译有错误的话，可以把错误信息贴出来
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/poboke/ActivatePowerMode/issues/10#issuecomment-165379038.

没有改名，是不是我这边哪里有问题，我也不清楚

点按以下载
 https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FARaPUuiUcXyQexjaVHLbI6sMUq3sAae6EFzI2j8zsd1LbRr-yXfyRSG8%2F%24%7Bf%7D%3Fo%3DAkX-kwPr28ejFGyHn5R7KyUK3OPA4kPMpeWe6x6PKXrm%26v%3D1%26x%3D3%26a%3DBYA3S1eOQuzuA656MAEA_wHIAP82lIte%26e%3D1452931980%26k%3D%24%7Buk%7D%26fl%3D%26r%3DF9CEBAAC-9432-419B-8212-545ACA77DB3D-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D65165152-0B40-44CA-AFBB-DAC2C0FD6638%26p%3D7%26s%3DrQEbBjj-sgjR4rc4YRYWhQYf0nQ&uk=vf4RrjqmClBy89qC-9Kqbw&f=%E6%9C%AA%E5%91%BD%E5%90%8D.mov&sz=27505848未命名.mov
27.5 MB

**Comment by poboke** [comment]
你在ActivatePowerMode点右键选择`Open in Finder`：
<img width="267" alt="1111111" src="https://cloud.githubusercontent.com/assets/4415086/11864670/93dd2306-a4d9-11e5-970b-2565a4db958b.png">
然后双击`ActivatePowerMode.xcodeproj`打开工程。

**Comment by manfar** [comment]
> 在 2015年12月17日，下午4:19，poboke notifications@github.com 写道：
> 
> 你在ActivatePowerMode点右键选择Open in Finder：
>  https://cloud.githubusercontent.com/assets/4415086/11864670/93dd2306-a4d9-11e5-970b-2565a4db958b.png
> 然后双击ActivatePowerMode.xcodeproj打开工程。
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/poboke/ActivatePowerMode/issues/10#issuecomment-165380880.

打开了之后，我按住command +b ,提示成功，退出Xcode之后，从新打开Xcode，没有发现什么提示

**Comment by poboke** [comment]
要完全退出Xcode

**Comment by manfar** [comment]
> 在 2015年12月17日，下午4:39，Me Mac joycle@yahoo.com 写道：
> 
> > 在 2015年12月17日，下午4:36，poboke <notifications@github.com <mailto:notifications@github.com>> 写道：
> > 
> > 要完全退出Xcode
> > 
> > —
> > Reply to this email directly or view it on GitHub https://github.com/poboke/ActivatePowerMode/issues/10#issuecomment-165383941.
> > 
> > 按您说的，打开工程，按command + b编译，然后完全退出Xcode，可是       “在任务栏用右键退出”     这是哪里？不是左上角的Xcode——quit Xcode？

在dock 栏里推出了，也不行，好奇怪

**Comment by manfar** [comment]
> 在 2015年12月17日，下午4:41，Me Mac joycle@yahoo.com 写道：
> 
> > 在 2015年12月17日，下午4:39，Me Mac <joycle@yahoo.com <mailto:joycle@yahoo.com>> 写道：
> > 
> > > 在 2015年12月17日，下午4:36，poboke <notifications@github.com <mailto:notifications@github.com>> 写道：
> > > 
> > > 要完全退出Xcode
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub https://github.com/poboke/ActivatePowerMode/issues/10#issuecomment-165383941.
> > > 
> > > 按您说的，打开工程，按command + b编译，然后完全退出Xcode，可是       “在任务栏用右键退出”     这是哪里？不是左上角的Xcode——quit Xcode？
> 
> 在dock 栏里推出了，也不行，好奇怪

从12点半到现在差不多我整了五个小时了，没反应

**Comment by manfar** [comment]
> 在 2015年12月17日，下午4:41，Me Mac <joycle@yahoo.com <mailto:joycle@yahoo.com>> 写道：
> 
> > 在 2015年12月17日，下午4:39，Me Mac <joycle@yahoo.com <mailto:joycle@yahoo.com>> 写道：
> > 
> > > 在 2015年12月17日，下午4:36，poboke <notifications@github.com <mailto:notifications@github.com>> 写道：
> > > 
> > > 要完全退出Xcode
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub https://github.com/poboke/ActivatePowerMode/issues/10#issuecomment-165383941.
> > > 
> > > 按您说的，打开工程，按command + b编译，然后完全退出Xcode，可是       “在任务栏用右键退出”     这是哪里？不是左上角的Xcode——quit Xcode？
> 
> 在dock 栏里推出了，也不行，好奇怪

从12点半到现在差不多我整了五个小时了，没反应

**Comment by poboke** [comment]
你加我qq吧
