### ISSUE TITLE
有一个bug

### ISSUE THREAD

**Issue by bijy** [poboke/ActivatePowerMode#11]
当代码有警告的时候，点击左侧的警告按钮，爆了下火花。但是确没办法选择警告里的选项了。

**Comment by poboke** [comment]
经过调试，这是震屏效果导致的。
当你点击警告时，Xcode会弹出一个修正错误的浮动框。
这时如果屏幕震动会导致浮动框失去焦点，所以浮动框消失，代码也就没有修正了。
我看看怎么解决吧。

**Comment by poboke** [comment]
最新代码已解决
