### ISSUE TITLE
又有一个bug...

### ISSUE THREAD

**Issue by turtleeeeee** [poboke/ActivatePowerMode#13]
在代码自动提示的时候，想按键盘的上下箭头去选择提示菜单里的提示代码的时候＝ ＝，多摁几下箭头提示菜单会消失＝ ＝

**Comment by poboke** [comment]
这个也是震屏效果引起的。
震屏时，代码补全框会短暂消失又出现，当你快速按两下箭头时：
- 第一次按键引起震屏，所以补全框消失。
- 第二次按键按键，因为补全框不见了，所以箭头就跳到其它代码行去了。

目前可以先把震屏效果关了。

**Comment by DangerousDON** [comment]
代码补全功能如果慢慢地一下一下来还能用，如果快速按上下箭头就会打断补全提示了。

**Comment by turtleeeeee** [comment]
怎么把震屏效果关了啊？？

**Comment by poboke** [comment]
可以在菜单里关闭：

![](https://github.com/poboke/ActivatePowerMode/raw/master/Screenshots/switch.png)

**Comment by poboke** [comment]
最新代码已解决
