### ISSUE TITLE
Xcode6.1 已安装但Plugin菜单没有选项

### ISSUE THREAD

**Issue by Lazy6Studio** [poboke/ActivatePowerMode#18]
我表示重启过了╮(╯_╰)╭

**Comment by poboke** [comment]
一般都是由于安装步骤不正确导致的，可以重新按下面步骤操作：

1、先完全退出Xcode，再删掉插件。
2、打开Xcode，再完全退出Xcode。
3、重新编译安装插件，再打开Xcode。
4、这时可以看到加载插件的弹出框，点击load按钮就可以了。

**Comment by Lazy6Studio** [comment]
@poboke 自动装的……乃是说手动编译一次？

**Comment by poboke** [comment]
是的，手动编译可以看到有没有报错。

**Comment by Lazy6Studio** [comment]
@poboke 报了15个错……

**Comment by poboke** [comment]
你的Xcode不要改名，不然编译时会找不到路径，你可以改为`Xcode.app`。

也可以到[https://github.com/poboke/ActivatePowerMode/releases](https://github.com/poboke/ActivatePowerMode/releases)下载编译好的插件，
放到`~/Library/Application Support/Developer/Shared/Xcode/Plug-ins`目录里。

**Comment by Lazy6Studio** [comment]
@poboke 并没有给Xcode改名，现在发现是无论自己编译还是通过包管理器下载下来的插件，MacOS和Resources里面都是空的。至于报错，并不是报找不到路径
![image](https://cloud.githubusercontent.com/assets/6430268/12061619/e6a6fb2e-afc5-11e5-964f-bbb38ad18b87.png)

**Comment by poboke** [comment]
我只在6.4编译过，不知道6.1可不可以。
你可以下载编译好的插件试试。

**Comment by Lazy6Studio** [comment]
@poboke 编译好的能用，没问题
