### ISSUE TITLE
JetBrains IDEA

### ISSUE THREAD

**Issue by kluevandrew** [poboke/ActivatePowerMode#9]
please!

**Comment by poboke** [comment]
Sorry, I don't know how to make a plugin for IDEA.
You can see some `power mode` plugins to other editors at this url 
[https://github.com/codeinthedark/awesome-power-mode](https://github.com/codeinthedark/awesome-power-mode).
You may see it one day.

**Comment by poboke** [comment]
I found a plugin for IDEA.
[https://github.com/ViceFantasyPlace/activate-power-mode](https://github.com/ViceFantasyPlace/activate-power-mode)

**Comment by kluevandrew** [comment]
oh! that's great! Thankl you!
